# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - conference-api-demo

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_af19e4e43c1f49d9a3c9b2f667a37d31 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6d6d7a29b8ab4a32bbcd297691b4e837 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.AzureAppService_ContainerUsername_af19e4e43c1f49d9a3c9b2f667a37d31 }}/jmayorga94/devsessions:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'conference-api-demo'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6e3637a8c6d04da6a970ae1ed5ed8c91 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_af19e4e43c1f49d9a3c9b2f667a37d31 }}/jmayorga94/devsessions:${{ github.sha }}'